/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.experts.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QuestionAssignment service. Represents a row in the &quot;Experts_QuestionAssignment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.experts.model.impl.QuestionAssignmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.experts.model.impl.QuestionAssignmentImpl}.
 * </p>
 *
 * @author Ryan Park
 * @see QuestionAssignment
 * @see com.liferay.experts.model.impl.QuestionAssignmentImpl
 * @see com.liferay.experts.model.impl.QuestionAssignmentModelImpl
 * @generated
 */
public interface QuestionAssignmentModel extends BaseModel<QuestionAssignment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a question assignment model instance should use the {@link QuestionAssignment} interface instead.
	 */

	/**
	 * Returns the primary key of this question assignment.
	 *
	 * @return the primary key of this question assignment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this question assignment.
	 *
	 * @param primaryKey the primary key of this question assignment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the question assignment ID of this question assignment.
	 *
	 * @return the question assignment ID of this question assignment
	 */
	public long getQuestionAssignmentId();

	/**
	 * Sets the question assignment ID of this question assignment.
	 *
	 * @param questionAssignmentId the question assignment ID of this question assignment
	 */
	public void setQuestionAssignmentId(long questionAssignmentId);

	/**
	 * Returns the company ID of this question assignment.
	 *
	 * @return the company ID of this question assignment
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this question assignment.
	 *
	 * @param companyId the company ID of this question assignment
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this question assignment.
	 *
	 * @return the user ID of this question assignment
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this question assignment.
	 *
	 * @param userId the user ID of this question assignment
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this question assignment.
	 *
	 * @return the user uuid of this question assignment
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this question assignment.
	 *
	 * @param userUuid the user uuid of this question assignment
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this question assignment.
	 *
	 * @return the user name of this question assignment
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this question assignment.
	 *
	 * @param userName the user name of this question assignment
	 */
	public void setUserName(String userName);

	/**
	 * Returns the modified date of this question assignment.
	 *
	 * @return the modified date of this question assignment
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this question assignment.
	 *
	 * @param modifiedDate the modified date of this question assignment
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the question ID of this question assignment.
	 *
	 * @return the question ID of this question assignment
	 */
	public long getQuestionId();

	/**
	 * Sets the question ID of this question assignment.
	 *
	 * @param questionId the question ID of this question assignment
	 */
	public void setQuestionId(long questionId);

	/**
	 * Returns the locked of this question assignment.
	 *
	 * @return the locked of this question assignment
	 */
	public boolean getLocked();

	/**
	 * Returns <code>true</code> if this question assignment is locked.
	 *
	 * @return <code>true</code> if this question assignment is locked; <code>false</code> otherwise
	 */
	public boolean isLocked();

	/**
	 * Sets whether this question assignment is locked.
	 *
	 * @param locked the locked of this question assignment
	 */
	public void setLocked(boolean locked);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(QuestionAssignment questionAssignment);

	public int hashCode();

	public CacheModel<QuestionAssignment> toCacheModel();

	public QuestionAssignment toEscapedModel();

	public String toString();

	public String toXmlString();
}